# Generated by Django 5.0.7 on 2024-08-06 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='video_app.basemodel')),
                ('title', models.CharField(max_length=100)),
                ('video_file', models.FileField(upload_to='files/')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='files/pdf/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('video_app.basemodel',),
        ),
    ]
